#!/usr/bin/env python3
"""
Setup Script for Azure Speech Service Text-to-Speech

This script helps users set up the Azure Speech Service TTS application
by guiding them through the configuration process.

Usage:
    python setup.py
"""

import os
import sys

def print_banner():
    """Print the setup banner."""
    print("=" * 70)
    print("🎤 Azure Speech Service - Text-to-Speech Setup")
    print("=" * 70)
    print()

def check_python_version():
    """Check if Python version is compatible."""
    if sys.version_info < (3, 7):
        print("❌ Error: Python 3.7 or higher is required.")
        print(f"Current version: {sys.version}")
        return False
    print(f"✅ Python version check passed: {sys.version_info.major}.{sys.version_info.minor}")
    return True

def install_requirements():
    """Install required packages."""
    print("\n📦 Installing required packages...")
    try:
        import subprocess
        result = subprocess.run([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"], 
                              capture_output=True, text=True)
        if result.returncode == 0:
            print("✅ Successfully installed required packages")
            return True
        else:
            print(f"❌ Failed to install packages: {result.stderr}")
            return False
    except Exception as e:
        print(f"❌ Error installing packages: {e}")
        return False

def create_config_file():
    """Create configuration file from template."""
    print("\n⚙️ Setting up configuration...")
    
    if os.path.exists("config.py"):
        overwrite = input("Config file already exists. Overwrite? (y/n): ").strip().lower()
        if overwrite not in ['y', 'yes']:
            print("Keeping existing config file.")
            return True
    
    print("\nPlease provide your Azure Speech Service credentials:")
    print("(You can find these in your Azure Portal > Speech Service resource)")
    
    speech_key = input("Enter your Speech Service Key: ").strip()
    if not speech_key:
        print("❌ Speech key is required")
        return False
    
    endpoint = input("Enter your Endpoint (e.g., https://eastus.api.cognitive.microsoft.com/): ").strip()
    if not endpoint:
        print("❌ Endpoint is required")
        return False
    
    # Ensure endpoint ends with /
    if not endpoint.endswith('/'):
        endpoint += '/'
    
    # Voice selection
    print("\nSelect default voice:")
    print("1. Andrew (Male)")
    print("2. Ava (Female)")
    voice_choice = input("Enter choice (1 or 2): ").strip()
    
    if voice_choice == "2":
        default_voice = "en-US-AvaMultilingualNeural"
    else:
        default_voice = "en-US-AndrewMultilingualNeural"
    
    # Create config file
    config_content = f'''# Azure Speech Service Configuration
# Generated by setup script

# Azure Speech Service Credentials
SPEECH_KEY = "{speech_key}"
SPEECH_ENDPOINT = "{endpoint}"

# Voice Configuration
DEFAULT_VOICE = "{default_voice}"

# Output Settings
DEFAULT_OUTPUT_FOLDER = "output"
DEFAULT_FILENAME_PREFIX = "speech_output"
'''
    
    try:
        with open("config.py", "w") as f:
            f.write(config_content)
        print("✅ Configuration file created successfully")
        return True
    except Exception as e:
        print(f"❌ Error creating config file: {e}")
        return False

def create_output_directory():
    """Create output directory for audio files."""
    if not os.path.exists("output"):
        try:
            os.makedirs("output")
            print("✅ Created output directory")
        except Exception as e:
            print(f"❌ Error creating output directory: {e}")
            return False
    return True

def test_configuration():
    """Test the configuration by attempting to import and initialize."""
    print("\n🧪 Testing configuration...")
    try:
        import azure.cognitiveservices.speech as speechsdk
        print("✅ Azure Speech SDK imported successfully")
        
        # Try to import config
        import config
        speech_config = speechsdk.SpeechConfig(
            subscription=config.SPEECH_KEY,
            endpoint=config.SPEECH_ENDPOINT
        )
        print("✅ Configuration loaded successfully")
        return True
    except ImportError as e:
        print(f"❌ Import error: {e}")
        return False
    except Exception as e:
        print(f"❌ Configuration error: {e}")
        return False

def display_next_steps():
    """Display next steps for the user."""
    print("\n" + "=" * 70)
    print("🎉 Setup completed successfully!")
    print("=" * 70)
    print("\n📋 Next steps:")
    print("1. Run the basic version:")
    print("   python speech_synthesis.py")
    print("\n2. Run the advanced version with custom voices:")
    print("   python speech_synthesis_custom_voice.py")
    print("\n3. Check the README.md for detailed usage instructions")
    print("\n💡 Tips:")
    print("- Your audio files will be saved in the 'output' folder")
    print("- You can modify config.py to change your settings")
    print("- Check the Azure portal for usage and billing information")
    print("\n" + "=" * 70)

def main():
    """Main setup function."""
    print_banner()
    
    # Check Python version
    if not check_python_version():
        return False
    
    # Install requirements
    if not install_requirements():
        print("\n💡 You can manually install requirements with:")
        print("pip install azure-cognitiveservices-speech")
        proceed = input("\nProceed with setup anyway? (y/n): ").strip().lower()
        if proceed not in ['y', 'yes']:
            return False
    
    # Create config file
    if not create_config_file():
        return False
    
    # Create output directory
    create_output_directory()
    
    # Test configuration
    if test_configuration():
        display_next_steps()
        return True
    else:
        print("\n⚠️ Setup completed but configuration test failed.")
        print("Please check your credentials and try running the script manually.")
        return False

if __name__ == "__main__":
    success = main()
    if not success:
        print("\n❌ Setup failed. Please check the error messages above.")
        sys.exit(1)
